In [1]:
import torch

x = torch.ones(3,4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [2]:
x.type()

'torch.FloatTensor'

In [3]:
x = torch.ones((3,4), dtype=torch.int16)
print(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int16)


In [4]:
y = torch.zeros(3,4)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [6]:
y.type()

'torch.FloatTensor'