In [1]:
import torch

x = torch.ones(3,4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [2]:
x.type()

'torch.FloatTensor'

In [3]:
x = torch.ones((3,4), dtype=torch.int16)
print(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int16)


In [4]:
y = torch.zeros(3,4)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [6]:
y.type()

'torch.FloatTensor'

In [10]:
import torch

x = torch.tensor([[1,2,3], [4,5,6]])
print(x)
y = x.reshape(3,2)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [13]:
import torch

x = torch.tensor([[1,2,3], [4,5,6]])
y = x.transpose(0,1)

print(y)
print(x.size())
print(y.size())

tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 3])
torch.Size([3, 2])


In [29]:
import torch

x = torch.randn((3,1,5,4))
print(x.dim())

y = x.squeeze()
print(y.dim())
print(y.size())

4
3
torch.Size([3, 5, 4])


In [32]:
import torch

x = torch.randn(3,2)
print(x)

print(x.view(2,3))

tensor([[ 0.4465, -2.0372],
        [ 0.0204, -0.3319],
        [-0.1705,  0.2857]])
tensor([[ 0.4465, -2.0372,  0.0204],
        [-0.3319, -0.1705,  0.2857]])


In [35]:
x = torch.ones((3,2), dtype=torch.int)
print(x)

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)


In [40]:
import torch

x = torch.randn((3))
print(x.size())

print(x.unsqueeze(0).size())
print(x.unsqueeze(0))

torch.Size([3])
torch.Size([1, 3])
tensor([[-0.4292,  2.4771, -0.3261]])


In [41]:
import torch
x = torch.ones(1)
print(x)
print(x.item())

tensor([1.])
1.0


In [47]:
import torch
x = torch.tensor(
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]], dtype=torch.float32)
x.size()

torch.Size([4, 3, 3])

In [48]:
print(x)

tensor([[[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.1000],
         [0.7000, 0.6000, 0.5000]],

        [[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.2000],
         [0.7000, 0.6000, 0.5000]],

        [[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.1000],
         [0.5000, 0.6000, 0.7000]],

        [[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.2000],
         [0.5000, 0.6000, 0.7000]]])
