In [6]:
import torch
x = torch.rand(15)
print(x)
print(x[2:])

tensor([0.7609, 0.1998, 0.2577, 0.8797, 0.1056, 0.7426, 0.2801, 0.0139, 0.9657,
        0.2904, 0.0305, 0.4417, 0.9692, 0.1410, 0.5157])
tensor([0.2577, 0.8797, 0.1056, 0.7426, 0.2801, 0.0139, 0.9657, 0.2904, 0.0305,
        0.4417, 0.9692, 0.1410, 0.5157])


In [30]:
import torch
x = torch.randn((6,5))
print(x)
print(x[::2, ::2])

tensor([[ 0.9992,  0.1180, -1.8617, -0.6896, -0.1249],
        [ 1.6253,  1.0461, -1.2190,  2.0096, -0.1222],
        [ 0.4819,  1.1721,  1.6283,  0.9586,  0.5938],
        [ 1.8138, -0.4025, -1.1225, -0.2365, -0.6164],
        [-0.2785, -0.0611, -0.3382, -0.4430,  0.0557],
        [-0.0643,  0.2405, -0.7107, -0.8943, -1.7230]])
tensor([[ 0.9992, -1.8617, -0.1249],
        [ 0.4819,  1.6283,  0.5938],
        [-0.2785, -0.3382,  0.0557]])
