In [6]:
import torch
x = torch.rand(15)
print(x)
print(x[2:])

tensor([0.7609, 0.1998, 0.2577, 0.8797, 0.1056, 0.7426, 0.2801, 0.0139, 0.9657,
        0.2904, 0.0305, 0.4417, 0.9692, 0.1410, 0.5157])
tensor([0.2577, 0.8797, 0.1056, 0.7426, 0.2801, 0.0139, 0.9657, 0.2904, 0.0305,
        0.4417, 0.9692, 0.1410, 0.5157])


In [25]:
import torch
x = torch.randn((6,5))
print(x)
print(x[1:5:2, 0:4:2])

tensor([[-0.5209,  0.4243,  0.1540, -0.7814, -1.7005],
        [-0.3191,  0.8843, -0.8301,  0.7414,  0.1033],
        [ 0.7716, -0.5891, -0.0888, -1.7860, -0.6578],
        [-1.3299,  0.5717,  0.9497, -0.3050,  0.4296],
        [ 1.7669,  1.1072,  0.0752,  0.9620,  0.0327],
        [ 0.3993,  1.0661,  1.3593, -1.5693,  0.2993]])
tensor([[-0.3191, -0.8301],
        [-1.3299,  0.9497]])
